// <auto-generated />
using System;
using FluxoCaixaDiario.Lancamentos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxoCaixaDiario.Lancamentos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LancamentosDbContext))]
    [Migration("20260610165733_AddLancamentoAuditFields")]
    partial class AddLancamentoAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixaDiario.Lancamentos.Domain.Entities.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("IX_Lancamentos_Data");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Lancamentos_IdempotencyKey")
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Lancamentos_Status");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("FluxoCaixaDiario.SharedKernel.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DadosEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosSaida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DuracaoMs")
                        .HasColumnType("bigint");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Servico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioOuChave")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLogs_CorrelationId");

                    b.HasIndex("OcorridoEm")
                        .HasDatabaseName("IX_AuditLogs_OcorridoEm");

                    b.HasIndex("Operacao")
                        .HasDatabaseName("IX_AuditLogs_Operacao");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("FluxoCaixaDiario.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("TentativasRetry")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessadoEm")
                        .HasDatabaseName("IX_OutboxMessages_ProcessadoEm");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("FluxoCaixaDiario.Lancamentos.Domain.Entities.Lancamento", b =>
                {
                    b.OwnsOne("FluxoCaixaDiario.Lancamentos.Domain.ValueObjects.Valor", "Valor", b1 =>
                        {
                            b1.Property<Guid>("LancamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Quantia")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.HasKey("LancamentoId");

                            b1.ToTable("Lancamentos");

                            b1.WithOwner()
                                .HasForeignKey("LancamentoId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
