// <auto-generated />
using System;
using FluxoCaixaDiario.Consolidado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxoCaixaDiario.Consolidado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConsolidadoDbContext))]
    [Migration("20260610112759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixaDiario.Consolidado.Domain.Entities.ConsolidadoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("QuantidadeLancamentos")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .IsUnique()
                        .HasDatabaseName("IX_ConsolidadoDiario_Data");

                    b.ToTable("ConsolidadoDiario", (string)null);
                });

            modelBuilder.Entity("FluxoCaixaDiario.Consolidado.Domain.Entities.EventoProcessado", b =>
                {
                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("LancamentoId", "EventType");

                    b.ToTable("EventosProcessados", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
