// <auto-generated />
using System;
using FluxoCaixaDiario.Consolidado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxoCaixaDiario.Consolidado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConsolidadoDbContext))]
    partial class ConsolidadoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixaDiario.SharedKernel.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DadosEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosSaida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DuracaoMs")
                        .HasColumnType("bigint");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Servico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioOuChave")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLogs_CorrelationId");

                    b.HasIndex("Operacao")
                        .HasDatabaseName("IX_AuditLogs_Operacao");

                    b.HasIndex("OcorridoEm")
                        .HasDatabaseName("IX_AuditLogs_OcorridoEm");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("FluxoCaixaDiario.Consolidado.Domain.Entities.ConsolidadoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("QuantidadeLancamentos")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .IsUnique()
                        .HasDatabaseName("IX_ConsolidadoDiario_Data");

                    b.ToTable("ConsolidadoDiario", (string)null);
                });

            modelBuilder.Entity("FluxoCaixaDiario.Consolidado.Domain.Entities.EventoProcessado", b =>
                {
                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("LancamentoId", "EventType");

                    b.ToTable("EventosProcessados", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
